name: ci-dockerfile

on:
  push:
    paths-ignore:
    - '**/README.md'
    branches:
    - '**'
  pull_request:
    paths-ignore:
    - '**/README.md'
    branches:
    - master

jobs:
  build:
   runs-on: ubuntu-latest
  
   steps:
     - uses: actions/checkout@v4
     - name: Build Docker image 
       run: docker build -t electrumx-firo .
     - name: Build Docker Compose
       run: |
       sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
       sudo chmod +x /usr/local/bin/docker-compose
       docker-compose build