name: ci-dockerfile

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build:
   runs-on: ubuntu-latest
  
   steps:
     - uses: actions/checkout@v4
     - name: Build Docker image 
       run: docker build -t electrumx-firo .
