name: ci-dockerfile

on:
  push:
    paths-ignore:
    - '**.md'
    branches:
    - '**'
  pull_request:
    paths-ignore:
    - '**.md'
    branches:
    - master

jobs:
  build:
   runs-on: ubuntu-latest
  
   steps:
     - uses: actions/checkout@v4
     - name: Build Docker image 
       run: docker build -t electrumx-firo .
